CREATE TABLE train(
	[date_time] [varchar](50) NULL,
	[site_name] [int] NULL,
	[posa_continent] [int] NULL,
	[user_location_country] [int] NULL,
	[user_location_region] [int] NULL,
	[user_location_city] [int] NULL,
	[orig_destination_distance] [varchar](50) NULL,
	[user_id] [int] NULL,
	[is_mobile] [bit] NULL,
	[is_package] [bit] NULL,
	[channel] [int] NULL,
	[srch_ci] [varchar](50) NULL,
	[srch_co] [varchar](50) NULL,
	[srch_adults_cnt] [int] NULL,
	[srch_children_cnt] [int] NULL,
	[srch_rm_cnt] [int] NULL,
	[srch_destination_id] [int] NULL,
	[srch_destination_type_id] [int] NULL,
	[hotel_continent] [int] NULL,
	[hotel_country] [int]NULL,
	[hotel_market] [int] NULL,
	[is_booking] [bit] NULL,
	[cnt] [bigint] NULL,
	[hotel_cluster] [int] NULL,
	)


	CREATE TABLE [dbo].[test](
		[id] [varchar](50) NULL,
		[date_time] [varchar](50) NULL,
		[site_name] [int] NULL,
		[posa_continent] [int] NULL,
		[user_location_country] [int] NULL,
		[user_location_region] [int] NULL,
		[user_location_city] [int] NULL,
		[orig_destination_distance] [varchar](50) NULL,
		[user_id] [int] NULL,
		[is_mobile] [bit] NULL,
		[is_package] [bit] NULL,
		[channel] [int] NULL,
		[srch_ci] [varchar](50) NULL,
		[srch_co] [varchar](50) NULL,
		[srch_adults_cnt] [int] NULL,
		[srch_children_cnt] [int] NULL,
		[srch_rm_cnt] [int] NULL,
		[srch_destination_id] [int] NULL,
		[srch_destination_type_id] [int] NULL,
		[hotel_continent] [int] NULL,
		[hotel_country] [int] NULL,
		[hotel_market] [int] NULL
	)
